// build.rs - Generates tools_impl.rs from separate tool definition files

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Generate into src/bridge/rmcp/generated/tools_impl.rs
    let dest_path = Path::new(&manifest_dir).join("src/bridge/rmcp/generated/tools_impl.rs");

    // Files to include (in order)
    let tool_files = vec![
        "src/bridge/rmcp/generated/memory_tools.rs",
        "src/bridge/rmcp/generated/experience_tools.rs",
        "src/bridge/rmcp/generated/reflection_tools.rs",
        "src/bridge/rmcp/generated/search_tools.rs",
        "src/bridge/rmcp/generated/ingestor_tools.rs",
        "src/bridge/rmcp/generated/agent_tools.rs",
        "src/bridge/rmcp/generated/hypothesis_tools.rs",
        "src/bridge/rmcp/generated/knowledge_tools.rs",
        "src/bridge/rmcp/generated/planner_tools.rs",
        "src/bridge/rmcp/generated/workflow_tools.rs",
        "src/bridge/rmcp/generated/exploration_tools.rs",
        "src/bridge/rmcp/generated/skills_tools.rs",
    ];

    let mut combined = String::new();

    // Add header with necessary imports
    combined.push_str(
        r#"// Auto-generated file - DO NOT EDIT
// Generated by build.rs

use std::sync::Arc;
use crate::tools::{self, ToolOutput};
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::ContentBlock;
use rmcp::tool_handler;
use rmcp::tool_router;
use rmcp::tool;

#[tool_router]
impl McpServerHandler {
"#,
    );

    // Read and combine all tool files
    for file_path in &tool_files {
        let full_path = Path::new(&manifest_dir).join(file_path);
        if let Ok(content) = fs::read_to_string(&full_path) {
            // Strip the header (comment + use statements + impl block start) and base indentation
            let adjusted = strip_tool_file_header(&content, 4);
            combined.push_str(&adjusted);
            combined.push('\n');
        } else {
            eprintln!("Warning: Could not read {}", full_path.display());
        }
    }

    combined.push_str(
        r#"
}

// Manual ServerHandler impl with custom server info
#[tool_handler]
impl rmcp::handler::server::ServerHandler for McpServerHandler {
    fn get_info(&self) -> rmcp::model::ServerInfo {
        use rmcp::model::ServerCapabilities;

        let capabilities = ServerCapabilities::builder()
            .enable_experimental()
            .enable_extensions()
            .enable_completions()
            .enable_prompts()
            .enable_resources()
            .enable_tasks()
            .enable_tools()
            .enable_tool_list_changed()
            .build();

        rmcp::model::ServerInfo::new(capabilities)
            .with_server_info(rmcp::model::Implementation::new(&self.name, &self.version))
    }
}
"#,
    );

    // Ensure parent directory exists
    if let Some(parent) = dest_path.parent() {
        fs::create_dir_all(parent).ok();
    }

    fs::write(&dest_path, combined).unwrap();
    println!("Generated {}", dest_path.display());

    // Tell Cargo to rerun the build script if any tool file changes
    for file_path in &tool_files {
        println!("cargo:rerun-if-changed={}", file_path);
    }
}

fn strip_tool_file_header(content: &str, base_spaces: usize) -> String {
    let base_indent = " ".repeat(base_spaces);
    let lines: Vec<&str> = content.lines().collect();
    let mut result_lines = Vec::new();
    let mut in_impl = false;
    let mut last_line_idx: Option<usize> = None;

    // Find the last non-empty line to determine if it's the closing brace
    for (idx, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if !trimmed.is_empty() {
            last_line_idx = Some(idx);
        }
    }

    for (idx, line) in lines.iter().enumerate() {
        let trimmed = line.trim();

        // Skip comment header lines (lines starting with //)
        if trimmed.starts_with("//") {
            continue;
        }

        // Skip use statements
        if trimmed.starts_with("use ") {
            continue;
        }

        // Skip the #[tool_router] attribute and impl line
        if trimmed.starts_with("#[tool_router]") {
            in_impl = true;
            continue;
        }
        if trimmed == "impl McpServerHandler {" {
            continue;
        }

        // Skip the final closing brace of the impl block
        if in_impl && Some(idx) == last_line_idx && trimmed == "}" {
            continue;
        }

        // Remove base indentation and add line
        if line.starts_with(&base_indent) {
            result_lines.push(&line[base_spaces..]);
        } else if trimmed.is_empty() {
            result_lines.push("");
        } else {
            result_lines.push(line.trim_start());
        }
    }

    result_lines.join("\n")
}
