// build.rs - Generates tools_impl.rs from separate tool definition files

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    
    // Generate into src/bridge/rmcp/generated/tools_impl.rs
    let dest_path = Path::new(&manifest_dir).join("src/bridge/rmcp/generated/tools_impl.rs");
    
    // Files to include (in order)
    let tool_files = vec![
        "src/bridge/rmcp/generated/memory_tools.rs",
        "src/bridge/rmcp/generated/experience_tools.rs",
        "src/bridge/rmcp/generated/reflection_tools.rs",
        "src/bridge/rmcp/generated/search_tools.rs",
        "src/bridge/rmcp/generated/ingestor_tools.rs",
        "src/bridge/rmcp/generated/agent_tools.rs",
        "src/bridge/rmcp/generated/hypothesis_tools.rs",
        "src/bridge/rmcp/generated/knowledge_tools.rs",
        "src/bridge/rmcp/generated/planner_tools.rs",
        "src/bridge/rmcp/generated/workflow_tools.rs",
        "src/bridge/rmcp/generated/exploration_tools.rs",
    ];
    
    let mut combined = String::new();
    
    // Add header with necessary imports
    combined.push_str(r#"// Auto-generated file - DO NOT EDIT
// Generated by build.rs

use std::sync::Arc;
use crate::bridge::rmcp::types::McpServerHandler;
use crate::tools::{self, ToolOutput};
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::ContentBlock;
use rmcp::tool_handler;
use rmcp::tool_router;
use rmcp::tool;

use crate::bridge::rmcp::helpers::{tool_output_to_content, enforcement_error_to_content};

#[tool_router]
impl McpServerHandler {
"#);

    // Read and combine all tool files
    for file_path in &tool_files {
        let full_path = Path::new(&manifest_dir).join(file_path);
        if let Ok(content) = fs::read_to_string(&full_path) {
            // Remove base indentation (tools are indented with 4 spaces in original)
            let adjusted = remove_base_indentation(&content, 4);
            combined.push_str(&adjusted);
            combined.push('\n');
        } else {
            eprintln!("Warning: Could not read {}", full_path.display());
        }
    }
    
    combined.push_str(r#"
}

// Manual ServerHandler impl with custom server info
#[tool_handler]
impl rmcp::handler::server::ServerHandler for McpServerHandler {
    fn get_info(&self) -> rmcp::model::ServerInfo {
        use rmcp::model::ServerCapabilitiesBuilder;

        #[allow(deprecated)]
        let capabilities = ServerCapabilitiesBuilder::default()
            .enable_experimental()
            .enable_extensions()
            .enable_logging()
            .enable_completions()
            .enable_prompts()
            .enable_resources()
            .enable_tasks()
            .enable_tools()
            .enable_tool_list_changed()
            .build();

        rmcp::model::ServerInfo::new(capabilities)
            .with_server_info(rmcp::model::Implementation::new(&self.name, &self.version))
    }
}
"#);
    
    // Ensure parent directory exists
    if let Some(parent) = dest_path.parent() {
        fs::create_dir_all(parent).ok();
    }
    
    fs::write(&dest_path, combined).unwrap();
    println!("Generated {}", dest_path.display());
    
    // Tell Cargo to rerun the build script if any tool file changes
    for file_path in &tool_files {
        println!("cargo:rerun-if-changed={}", file_path);
    }
}

fn remove_base_indentation(content: &str, base_spaces: usize) -> String {
    let base_indent = " ".repeat(base_spaces);
    content
        .lines()
        .map(|line| {
            if line.trim().is_empty() {
                String::new()
            } else if line.starts_with(&base_indent) {
                line[base_spaces..].to_string()
            } else {
                line.trim_start().to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
