"""Python replacement for Rust function_registry — complete with all 206+ tools."""

import json
from pathlib import Path
from typing import Any

FULL_REGISTRY = [
    # =========================================================================
    # Agent (5 tools)
    # =========================================================================
    {
        "id": "agent_get_workflow",
        "function_name": "get_workflow",
        "category": "Agent",
        "priority": 1,
        "requires_workflow": False,
        "expected_behavior": "Returns workflow rules",
    },
    {
        "id": "agent_list_tools",
        "function_name": "list_tools",
        "category": "Agent",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Lists all available tools",
    },
    {
        "id": "agent_get_tool",
        "function_name": "get_tool",
        "category": "Agent",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Returns tool definition",
    },
    {
        "id": "agent_connect_mcp",
        "function_name": "connect_mcp_server",
        "category": "Agent",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Connect to external MCP server",
    },
    {
        "id": "agent_call_tool",
        "function_name": "call_tool",
        "category": "Agent",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Call tool on connected MCP server",
    },
    {
        "id": "agent_run_goal",
        "function_name": "run_agent_goal",
        "category": "Agent",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run goal-driven agent loop",
    },
    # =========================================================================
    # ACP (16 tools)
    # =========================================================================
    {
        "id": "acp_list_agents",
        "function_name": "list_acp_agents",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "List all registered ACP agents",
    },
    {
        "id": "acp_agent_count",
        "function_name": "acp_agent_count",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get count of registered ACP agents",
    },
    {
        "id": "acp_router",
        "function_name": "acp_router",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get ACP router information",
    },
    {
        "id": "acp_registry",
        "function_name": "acp_registry",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get ACP registry information",
    },
    {
        "id": "acp_create_message",
        "function_name": "create_acp_message",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Create ACP message without routing",
    },
    {
        "id": "acp_route_message",
        "function_name": "route_acp_message",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Route ACP message to agent",
    },
    {
        "id": "acp_get_capabilities",
        "function_name": "get_agent_capabilities",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get capabilities of an ACP agent",
    },
    {
        "id": "acp_system_status",
        "function_name": "get_system_status",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get ACP system status",
    },
    {
        "id": "acp_register_agent",
        "function_name": "register_agent",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Register a new ACP agent",
    },
    {
        "id": "acp_unregister_agent",
        "function_name": "unregister_agent",
        "category": "ACP",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Unregister an ACP agent",
    },
    {
        "id": "acp_cleanup_sessions",
        "function_name": "cleanup_sessions",
        "category": "ACP",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Clean up expired workflow enforcement sessions",
    },
    {
        "id": "acp_get_session_state",
        "function_name": "get_session_state",
        "category": "ACP",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get workflow enforcement session state",
    },
    # =========================================================================
    # CoObOpLoop (42 tools)
    # =========================================================================
    {
        "id": "loop_enqueue_goal",
        "function_name": "cooboploop_enqueue_goal",
        "category": "CoObOpLoop",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Enqueue a new goal into the objective queue",
    },
    {
        "id": "loop_list_goals",
        "function_name": "cooboploop_list_goals",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List goals in the objective queue",
    },
    {
        "id": "loop_get_goal",
        "function_name": "cooboploop_get_goal",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get a specific goal by ID",
    },
    {
        "id": "loop_update_goal_status",
        "function_name": "cooboploop_update_goal_status",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Update the status of a goal",
    },
    {
        "id": "loop_evaluate_goal",
        "function_name": "cooboploop_evaluate_goal",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Evaluate a goal and compute its priority",
    },
    {
        "id": "loop_reprioritize",
        "function_name": "cooboploop_reprioritize_queue",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Reprioritize all goals in the queue",
    },
    {
        "id": "loop_set_priority_policy",
        "function_name": "cooboploop_set_priority_policy",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Set the priority policy for evaluation",
    },
    {
        "id": "loop_record_outcome",
        "function_name": "cooboploop_record_capability_outcome",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Record the outcome of a capability",
    },
    {
        "id": "loop_capability_assessment",
        "function_name": "cooboploop_get_capability_assessment",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the assessment of a capability",
    },
    {
        "id": "loop_list_capabilities",
        "function_name": "cooboploop_list_capabilities",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all capabilities",
    },
    {
        "id": "loop_promote_autonomy",
        "function_name": "cooboploop_promote_autonomy",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Promote autonomy for a capability",
    },
    {
        "id": "loop_start_loop",
        "function_name": "cooboploop_start_loop",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Start the CoObOpLoop",
    },
    {
        "id": "loop_stop_loop",
        "function_name": "cooboploop_stop_loop",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Stop the CoObOpLoop",
    },
    {
        "id": "loop_get_status",
        "function_name": "cooboploop_get_loop_status",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the current status of the CoObOpLoop",
    },
    {
        "id": "loop_run_cycle",
        "function_name": "cooboploop_run_single_cycle",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run a single cycle of the CoObOpLoop",
    },
    {
        "id": "loop_step",
        "function_name": "cooboploop_step_loop",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Advance to the next stage in the CoObOpLoop",
    },
    {
        "id": "loop_post_evaluation",
        "function_name": "cooboploop_run_post_task_evaluation",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run post-task evaluation for a goal",
    },
    {
        "id": "loop_get_idle_state",
        "function_name": "cooboploop_get_idle_state",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the current idle state",
    },
    {
        "id": "loop_configure_idle",
        "function_name": "cooboploop_configure_idle_reevaluation_interval",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Configure the idle reevaluation interval",
    },
    {
        "id": "loop_create_research",
        "function_name": "cooboploop_create_research_objective",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Create a research objective",
    },
    {
        "id": "loop_get_hardware",
        "function_name": "cooboploop_get_hardware_profile",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the hardware profile",
    },
    {
        "id": "loop_detect_hardware",
        "function_name": "cooboploop_detect_hardware_changes",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Detect hardware changes",
    },
    {
        "id": "loop_inspection",
        "function_name": "cooboploop_run_inspection",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run inspection on a target",
    },
    {
        "id": "loop_modification_boundary",
        "function_name": "cooboploop_get_modification_boundary",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the modification boundary",
    },
    {
        "id": "loop_set_modification_boundary",
        "function_name": "cooboploop_set_modification_boundary",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Set the modification boundary",
    },
    {
        "id": "loop_opportunity_intake",
        "function_name": "cooboploop_run_opportunity_intake",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run opportunity intake",
    },
    {
        "id": "loop_pending_opportunities",
        "function_name": "cooboploop_get_pending_external_opportunities",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get pending external opportunities",
    },
    {
        "id": "loop_set_autonomous",
        "function_name": "cooboploop_set_autonomous_mode",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Set autonomous mode",
    },
    {
        "id": "loop_get_autonomous",
        "function_name": "cooboploop_get_autonomous_mode",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get autonomous mode",
    },
    {
        "id": "loop_get_autonomy_levels",
        "function_name": "cooboploop_get_autonomy_levels",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get autonomy levels",
    },
    {
        "id": "loop_list_objectives",
        "function_name": "cooboploop_list_strategic_objectives",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List strategic objectives",
    },
    {
        "id": "loop_add_objective",
        "function_name": "cooboploop_add_strategic_objective",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a strategic objective",
    },
    {
        "id": "loop_remove_objective",
        "function_name": "cooboploop_remove_strategic_objective",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Remove a strategic objective",
    },
    {
        "id": "loop_objective_hierarchy",
        "function_name": "cooboploop_get_objective_hierarchy",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the objective hierarchy",
    },
    {
        "id": "loop_set_mission",
        "function_name": "cooboploop_set_mission",
        "category": "CoObOpLoop",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Set the mission",
    },
    {
        "id": "loop_source_discovery",
        "function_name": "cooboploop_run_source_discovery",
        "category": "CoObOpLoop",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Run source discovery to find new objectives",
    },
    # =========================================================================
    # Memory (9 tools)
    # =========================================================================
    {
        "id": "mem_store",
        "function_name": "store_memory",
        "category": "Memory",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Store a new memory",
    },
    {
        "id": "mem_search",
        "function_name": "search_memory",
        "category": "Memory",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Search memories by content query",
    },
    {
        "id": "mem_list",
        "function_name": "list_memories",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all memories with optional filtering",
    },
    {
        "id": "mem_get",
        "function_name": "get_memory",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Retrieve a specific memory by ID",
    },
    {
        "id": "mem_archive",
        "function_name": "archive_memory",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Archive a memory by ID",
    },
    {
        "id": "mem_delete",
        "function_name": "delete_memory_by_id",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Delete a memory by ID",
    },
    {
        "id": "mem_link",
        "function_name": "link_memories",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Create a relationship between two memories",
    },
    {
        "id": "mem_ranked_search",
        "function_name": "ranked_search",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search permanent memory with relevance ranking",
    },
    {
        "id": "mem_search_similar",
        "function_name": "search_similar",
        "category": "Memory",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search for similar memories using vector similarity",
    },
    # =========================================================================
    # Embeddings (6 tools)
    # =========================================================================
    {
        "id": "embed_store",
        "function_name": "store_embedding",
        "category": "Embeddings",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Store a vector embedding for semantic memory search",
    },
    {
        "id": "embed_get",
        "function_name": "get_embedding",
        "category": "Embeddings",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get an embedding by memory ID",
    },
    {
        "id": "embed_list",
        "function_name": "list_embeddings",
        "category": "Embeddings",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all memory embeddings",
    },
    {
        "id": "embed_delete",
        "function_name": "delete_embedding",
        "category": "Embeddings",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Delete an embedding by memory ID",
    },
    {
        "id": "embed_stats",
        "function_name": "get_embedding_stats",
        "category": "Embeddings",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get vector index statistics",
    },
    # =========================================================================
    # Experience (6 tools)
    # =========================================================================
    {
        "id": "exp_record",
        "function_name": "record_experience",
        "category": "Experience",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Record a new experience",
    },
    {
        "id": "exp_get",
        "function_name": "get_experience",
        "category": "Experience",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get a specific experience by ID",
    },
    {
        "id": "exp_list",
        "function_name": "list_experiences",
        "category": "Experience",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List recent experiences",
    },
    {
        "id": "exp_stats",
        "function_name": "get_experience_stats",
        "category": "Experience",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get statistics about recorded experiences",
    },
    {
        "id": "exp_add_evidence",
        "function_name": "add_evidence_to_experience",
        "category": "Experience",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add evidence to a recorded experience",
    },
    {
        "id": "exp_archive",
        "function_name": "archive_experience",
        "category": "Experience",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Archive an experience",
    },
    # =========================================================================
    # Knowledge (9 tools)
    # =========================================================================
    {
        "id": "know_add",
        "function_name": "add_knowledge",
        "category": "Knowledge",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Add new validated knowledge",
    },
    {
        "id": "know_query",
        "function_name": "query_knowledge",
        "category": "Knowledge",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Query the knowledge base",
    },
    {
        "id": "know_list",
        "function_name": "get_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get learned knowledge",
    },
    {
        "id": "know_stats",
        "function_name": "get_knowledge_stats",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get knowledge base statistics",
    },
    {
        "id": "know_mature",
        "function_name": "get_mature_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get mature knowledge",
    },
    {
        "id": "know_update",
        "function_name": "update_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Update an existing knowledge item",
    },
    {
        "id": "know_delete",
        "function_name": "delete_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Delete a knowledge item",
    },
    {
        "id": "know_related",
        "function_name": "get_related_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get knowledge items related to a given item",
    },
    {
        "id": "know_bump",
        "function_name": "bump_knowledge_version",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Bump the version of a knowledge item",
    },
    {
        "id": "know_set_status",
        "function_name": "set_knowledge_status",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Set knowledge status",
    },
    {
        "id": "know_add_relation",
        "function_name": "add_knowledge_relation",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a relation between two knowledge items",
    },
    {
        "id": "know_manage_dependency",
        "function_name": "manage_knowledge_dependency",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Manage knowledge dependencies",
    },
    {
        "id": "know_search_tag",
        "function_name": "search_knowledge_by_tag",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search knowledge by tag",
    },
    {
        "id": "know_validate_deps",
        "function_name": "validate_knowledge_dependencies",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Validate all knowledge dependencies",
    },
    {
        "id": "know_record_application",
        "function_name": "record_knowledge_application",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Record the result of applying knowledge",
    },
    {
        "id": "know_extract",
        "function_name": "extract_knowledge",
        "category": "Knowledge",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Extract supported hypothesis as reusable knowledge",
    },
    # =========================================================================
    # Exploration (12 tools)
    # =========================================================================
    {
        "id": "explore_start",
        "function_name": "start_exploration",
        "category": "Exploration",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Start a new exploration",
    },
    {
        "id": "explore_status",
        "function_name": "get_exploration_status",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the current status of an exploration",
    },
    {
        "id": "explore_pause",
        "function_name": "pause_exploration",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Pause an ongoing exploration",
    },
    {
        "id": "explore_resume",
        "function_name": "resume_exploration",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Resume a paused exploration",
    },
    {
        "id": "explore_complete",
        "function_name": "complete_exploration",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Complete an exploration with findings",
    },
    {
        "id": "explore_abandon",
        "function_name": "abandon_exploration",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Abandon an exploration without findings",
    },
    {
        "id": "explore_record_attempt",
        "function_name": "record_attempt",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Record an attempt during exploration",
    },
    {
        "id": "explore_add_hypothesis",
        "function_name": "add_hypothesis",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a hypothesis to an exploration",
    },
    {
        "id": "explore_create_hypothesis",
        "function_name": "create_hypothesis",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Create a testable hypothesis",
    },
    {
        "id": "explore_evaluate_hypothesis",
        "function_name": "evaluate_exploration_hypothesis",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Evaluate a hypothesis during exploration",
    },
    {
        "id": "explore_evaluate",
        "function_name": "evaluate_hypothesis",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Evaluate a hypothesis based on accumulated evidence",
    },
    {
        "id": "explore_promote_finding",
        "function_name": "promote_finding",
        "category": "Exploration",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Promote a finding to reusable knowledge",
    },
    # =========================================================================
    # Evidence (4 tools)
    # =========================================================================
    {
        "id": "evidence_add",
        "function_name": "add_evidence",
        "category": "Evidence",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add evidence to a hypothesis",
    },
    {
        "id": "evidence_get",
        "function_name": "get_evidence",
        "category": "Evidence",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get a specific evidence record",
    },
    {
        "id": "evidence_list",
        "function_name": "list_evidence",
        "category": "Evidence",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all evidence records",
    },
    {
        "id": "evidence_get_hypothesis",
        "function_name": "get_hypothesis",
        "category": "Evidence",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get details of a specific hypothesis",
    },
    # =========================================================================
    # Observations (3 tools)
    # =========================================================================
    {
        "id": "obs_record",
        "function_name": "record_observation",
        "category": "Observations",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Record an observation",
    },
    {
        "id": "obs_list",
        "function_name": "list_observations",
        "category": "Observations",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List recorded observations",
    },
    {
        "id": "obs_list_hypotheses",
        "function_name": "list_hypotheses",
        "category": "Observations",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all hypotheses",
    },
    # =========================================================================
    # Research (24 tools)
    # =========================================================================
    {
        "id": "research_full",
        "function_name": "research",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Full research pipeline",
    },
    {
        "id": "research_quick",
        "function_name": "quick_research",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Quick research (1-3 sources, <5s)",
    },
    {
        "id": "research_deep",
        "function_name": "deep_research",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Deep research (multi-iteration)",
    },
    {
        "id": "research_find_error",
        "function_name": "find_error_resolution",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Find error resolution via external search",
    },
    {
        "id": "research_web_search",
        "function_name": "web_search",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search the web using DuckDuckGo",
    },
    {
        "id": "research_web_open",
        "function_name": "web_open",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Open a web URL and retrieve content",
    },
    {
        "id": "research_web_extract",
        "function_name": "web_extract",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Extract clean text from URL via Jina",
    },
    {
        "id": "research_wikipedia",
        "function_name": "get_wikipedia",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Wikipedia for encyclopedic facts",
    },
    {
        "id": "research_news",
        "function_name": "search_news",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search current news sources",
    },
    {
        "id": "research_reddit",
        "function_name": "search_reddit",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Reddit discussions",
    },
    {
        "id": "research_hackernews",
        "function_name": "search_hackernews",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Hacker News tech community",
    },
    {
        "id": "research_youtube",
        "function_name": "search_youtube",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search YouTube videos",
    },
    {
        "id": "research_substack",
        "function_name": "search_substack",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Substack newsletter publications",
    },
    {
        "id": "research_bluesky",
        "function_name": "search_bluesky",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Bluesky social posts",
    },
    {
        "id": "research_telegram",
        "function_name": "search_telegram",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Telegram public channel messages",
    },
    {
        "id": "research_mastodon",
        "function_name": "search_mastodon",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Mastodon fediverse posts",
    },
    {
        "id": "research_vk",
        "function_name": "search_vk",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search VK social network",
    },
    {
        "id": "research_preprints",
        "function_name": "search_preprints",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search arXiv/bioRxiv/medRxiv preprints",
    },
    {
        "id": "research_datasets",
        "function_name": "search_datasets",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search Zenodo/Figshare/OSF datasets",
    },
    {
        "id": "research_osm",
        "function_name": "search_osm",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search OpenStreetMap geographic data",
    },
    {
        "id": "research_sec",
        "function_name": "search_sec_filings",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search SEC EDGAR financial filings",
    },
    {
        "id": "research_resurrect",
        "function_name": "resurrect_dead_link",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Recover broken links via Wayback Machine",
    },
    {
        "id": "research_verify_citations",
        "function_name": "verify_citations",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Verify citations via Crossref/OpenAlex",
    },
    {
        "id": "research_find_counter",
        "function_name": "find_counter_arguments",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Find opposing academic arguments",
    },
    {
        "id": "research_validate_bib",
        "function_name": "validate_bibliography",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Validate an entire reference list",
    },
    {
        "id": "research_format_citations",
        "function_name": "format_citations",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Format citations (BibTeX/APA/MLA/Chicago/RIS)",
    },
    {
        "id": "research_detect_trends",
        "function_name": "detect_trends",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Detect trending topics across platforms",
    },
    {
        "id": "research_score_reliability",
        "function_name": "score_reliability",
        "category": "Research",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Score source reliability",
    },
    # =========================================================================
    # Planning (7 tools)
    # =========================================================================
    {
        "id": "plan_create",
        "function_name": "create_plan",
        "category": "Planning",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Create a new task plan",
    },
    {
        "id": "plan_add_step",
        "function_name": "add_plan_step",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a step to an existing plan",
    },
    {
        "id": "plan_add_dependency",
        "function_name": "add_step_dependency",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a dependency between plan steps",
    },
    {
        "id": "plan_get",
        "function_name": "get_plan",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get a plan by ID",
    },
    {
        "id": "plan_list",
        "function_name": "list_plans",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all plans",
    },
    {
        "id": "plan_start",
        "function_name": "start_plan",
        "category": "Planning",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Start executing a plan",
    },
    {
        "id": "plan_complete_step",
        "function_name": "complete_step",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Mark a step as completed",
    },
    {
        "id": "plan_fail_step",
        "function_name": "fail_step",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Mark a step as failed",
    },
    {
        "id": "plan_cancel",
        "function_name": "cancel_plan",
        "category": "Planning",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Cancel a plan",
    },
    # =========================================================================
    # Skills (14 tools)
    # =========================================================================
    {
        "id": "skill_register",
        "function_name": "register_skill",
        "category": "Skills",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Register a new skill",
    },
    {
        "id": "skill_execute",
        "function_name": "execute_skill",
        "category": "Skills",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Execute a registered skill",
    },
    {
        "id": "skill_get",
        "function_name": "get_skill",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get skill details by ID",
    },
    {
        "id": "skill_list",
        "function_name": "list_skills",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all skills",
    },
    {
        "id": "skill_update_mastery",
        "function_name": "update_skill_mastery",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Update mastery level for a skill",
    },
    {
        "id": "skill_get_recommendations",
        "function_name": "get_skill_recommendations",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get recommended skills",
    },
    {
        "id": "skill_get_stats",
        "function_name": "get_skill_stats",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get skill statistics",
    },
    {
        "id": "skill_apply_decay",
        "function_name": "apply_skill_decay",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Apply decay to skill mastery",
    },
    {
        "id": "skill_enable_disable",
        "function_name": "enable_disable_skill",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Enable or disable a skill",
    },
    {
        "id": "skill_search",
        "function_name": "search_skills",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search skills by name or description",
    },
    {
        "id": "skill_get_metrics",
        "function_name": "get_skill_metrics",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get execution metrics for a skill",
    },
    {
        "id": "skill_get_unreliable",
        "function_name": "get_unreliable_skills",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List unreliable skills",
    },
    {
        "id": "skill_clear_metrics",
        "function_name": "clear_skill_metrics",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Clear execution metrics for a skill",
    },
    {
        "id": "skill_search_tag",
        "function_name": "search_skills_by_tag",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Search skills by tag",
    },
    {
        "id": "skill_discover",
        "function_name": "discover_skill",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Discover a new skill from experience",
    },
    {
        "id": "skill_unregister",
        "function_name": "unregister_skill",
        "category": "Skills",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Unregister a skill from the registry",
    },
    # =========================================================================
    # Workflow (7 tools)
    # =========================================================================
    {
        "id": "wf_create",
        "function_name": "create_workflow",
        "category": "Workflow",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Create a new workflow",
    },
    {
        "id": "wf_start",
        "function_name": "start_workflow",
        "category": "Workflow",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Start a workflow",
    },
    {
        "id": "wf_delete",
        "function_name": "delete_workflow",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Delete a workflow",
    },
    {
        "id": "wf_pause",
        "function_name": "pause_workflow",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Pause a running workflow",
    },
    {
        "id": "wf_resume",
        "function_name": "resume_workflow",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Resume a paused workflow",
    },
    {
        "id": "wf_cancel",
        "function_name": "cancel_workflow",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Cancel a workflow",
    },
    {
        "id": "wf_list",
        "function_name": "list_workflows",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all workflows",
    },
    {
        "id": "wf_step_add",
        "function_name": "add_workflow_step",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a step to a workflow",
    },
    {
        "id": "wf_variable_set",
        "function_name": "set_workflow_variable",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Set a variable on a workflow",
    },
    {
        "id": "wf_get_status",
        "function_name": "get_workflow_status",
        "category": "Workflow",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get the status of a workflow",
    },
    # =========================================================================
    # Ingest (5 tools)
    # =========================================================================
    {
        "id": "ingest_files",
        "function_name": "ingest_files",
        "category": "Ingest",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Ingest files from files_to_import folder",
    },
    {
        "id": "ingest_list",
        "function_name": "list_importable",
        "category": "Ingest",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List files available for import",
    },
    {
        "id": "ingest_list_ingested",
        "function_name": "list_ingested_files",
        "category": "Ingest",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List files that have been ingested",
    },
    {
        "id": "ingest_delete",
        "function_name": "delete_ingested_files",
        "category": "Ingest",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Delete original files after ingestion",
    },
    {
        "id": "ingest_transcribe",
        "function_name": "transcribe_audio",
        "category": "Ingest",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Transcribe an audio file to text using Whisper AI",
    },
    # =========================================================================
    # Reflection (6 tools)
    # =========================================================================
    {
        "id": "ref_create",
        "function_name": "create_reflection",
        "category": "Reflection",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Create a reflection on recent experiences",
    },
    {
        "id": "ref_insights",
        "function_name": "get_insights",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get actionable insights from past experiences",
    },
    {
        "id": "ref_patterns",
        "function_name": "analyze_patterns",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Analyze recent experiences for patterns",
    },
    {
        "id": "ref_list_patterns",
        "function_name": "get_patterns",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get detected patterns from analysis",
    },
    {
        "id": "ref_validate",
        "function_name": "validate_reflection",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Validate a reflection for quality and consistency",
    },
    {
        "id": "ref_list",
        "function_name": "list_reflections_by_status",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List reflections filtered by status",
    },
    {
        "id": "ref_update",
        "function_name": "update_reflection",
        "category": "Reflection",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Update an existing reflection",
    },
    # =========================================================================
    # World Model (10 tools)
    # =========================================================================
    {
        "id": "world_upsert",
        "function_name": "upsert_world_entity",
        "category": "WorldModel",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Create or update an entity in the world model",
    },
    {
        "id": "world_find",
        "function_name": "find_world_entity",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Find an entity by name",
    },
    {
        "id": "world_get",
        "function_name": "get_world_entity",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get an entity by its UUID",
    },
    {
        "id": "world_list",
        "function_name": "list_world_entities",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all entities of a given kind",
    },
    {
        "id": "world_relationship",
        "function_name": "add_world_relationship",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Add a typed relationship between two entities",
    },
    {
        "id": "world_get_relationships",
        "function_name": "get_world_relationships",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get all relationships involving an entity",
    },
    {
        "id": "world_get_dependencies",
        "function_name": "get_world_dependencies",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get what the given entity depends on",
    },
    {
        "id": "world_get_blockers",
        "function_name": "get_world_blockers",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get what entities block the given goal/entity",
    },
    {
        "id": "world_get_consumed",
        "function_name": "get_consumed_resources",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get what resources the given entity consumes",
    },
    {
        "id": "world_stats",
        "function_name": "get_world_model_stats",
        "category": "WorldModel",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get world-model statistics",
    },
    # =========================================================================
    # Personality (6 tools)
    # =========================================================================
    {
        "id": "pers_get",
        "function_name": "get_personality",
        "category": "Personality",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get current personality",
    },
    {
        "id": "pers_set_traits",
        "function_name": "set_personality_traits",
        "category": "Personality",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Update individual personality traits",
    },
    {
        "id": "pers_apply_preset",
        "function_name": "apply_personality_preset",
        "category": "Personality",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Apply a named personality preset",
    },
    {
        "id": "pers_list_presets",
        "function_name": "list_personality_presets",
        "category": "Personality",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "List all available personality presets",
    },
    {
        "id": "pers_get_decision",
        "function_name": "get_personality_decision",
        "category": "Personality",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get personality-driven decision",
    },
    {
        "id": "pers_format_response",
        "function_name": "format_response",
        "category": "Personality",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Format text content according to a communication style",
    },
    # =========================================================================
    # Background Workers (3 tools)
    # =========================================================================
    {
        "id": "worker_stats",
        "function_name": "get_worker_stats",
        "category": "BackgroundWorkers",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get background worker statistics",
    },
    {
        "id": "worker_count",
        "function_name": "get_worker_count",
        "category": "BackgroundWorkers",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Get the number of active background workers",
    },
    {
        "id": "worker_cleanup",
        "function_name": "cleanup_sessions",
        "category": "BackgroundWorkers",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Clean up expired workflow enforcement sessions",
    },
    # =========================================================================
    # Recommendations (2 tools)
    # =========================================================================
    {
        "id": "rec_get",
        "function_name": "get_recommendations",
        "category": "Recommendations",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get recommendations based on patterns and history",
    },
    {
        "id": "rec_get_reputation",
        "function_name": "get_reputation",
        "category": "Recommendations",
        "priority": 2,
        "requires_workflow": True,
        "expected_behavior": "Get reputation/quality score for a tool or approach",
    },
    # =========================================================================
    # Global Search (1 tool)
    # =========================================================================
    {
        "id": "search_global",
        "function_name": "global_search",
        "category": "Search",
        "priority": 1,
        "requires_workflow": True,
        "expected_behavior": "Search across all memories, experiences, and knowledge",
    },
]


class FunctionRegistry:
    def __init__(self):
        self.functions: list[dict[str, Any]] = FULL_REGISTRY

    def load(self, registry_path: Path | None = None):
        if registry_path is not None and registry_path.exists():
            with open(registry_path, "r", encoding="utf-8") as f:
                self.functions = json.load(f)

    def get_all(self) -> list[dict[str, Any]]:
        return self.functions

    def get_by_category(self, category: str) -> list[dict[str, Any]]:
        return [f for f in self.functions if f.get("category") == category]

    def get_untested(self, server_tools: list[str]) -> list[dict[str, Any]]:
        server_set = set(server_tools)
        return [f for f in self.functions if f["function_name"] not in server_set]
