//! Test modules
//!
//! Split from the monolithic tests.rs file for better maintainability.

pub mod acp;
pub mod agent;
pub mod agent_simulation;
pub mod audio_transcriber;
pub mod cli_tools;
pub mod concurrent_store;
pub mod context_pressure;
pub mod embeddings;
pub mod error_handling;
pub mod experience;
pub mod exploration_attempt;
pub mod exploration_finding;
pub mod exploration_hypothesis;
pub mod fresh_start;
pub mod hypothesis;
pub mod ingestor;
pub mod knowledge;
pub mod knowledge_query;
pub mod knowledge_store;
pub mod mcp_workflow;
pub mod memory;
pub mod memory_failure_isolation;
pub mod memory_retrieval;
pub mod observations;
pub mod personality;
pub mod planner;
pub mod queue_durability;
pub mod reflection;
pub mod rmcp;
pub mod search;
pub mod semantic_chunker;
pub mod session_smoke;
pub mod startup_durability;
pub mod workflow;

pub use acp::run_acp_tests;
pub use agent::run_agent_tests;
pub use agent_simulation::run_agent_simulation_tests;
pub use error_handling::run_error_handling_tests;
pub use experience::run_experience_tests;
pub use fresh_start::run_fresh_start_tests;
pub use hypothesis::run_hypothesis_tests;
pub use ingestor::run_ingestor_tests;
pub use knowledge::run_knowledge_tests;
pub use mcp_workflow::run_mcp_workflow_tests;
pub use memory::run_memory_tests;
pub use planner::run_planner_tests;
pub use reflection::run_reflection_tests;
pub use rmcp::run_rmcp_tests;
pub use search::run_search_tests;
pub use startup_durability::run_startup_durability_tests;
pub use workflow::run_workflow_tests;
